apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebpf-monitor-web
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ebpf-monitor-web
  template:
    metadata:
      labels:
        app: ebpf-monitor-web
    spec:
      containers:
        - name: ebpf-monitor-web
          image: ebpf-monitor:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 5000
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ebpf-secrets
                  key: secret_key
            - name: SMTP_SERVER
              value: smtp.example.com
            - name: SMTP_PORT
              value: "587"
            - name: EMAIL_SENDER
              value: alert@example.com
            - name: EMAIL_RECIPIENT
              value: recipient@example.com
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: ebpf-secrets
                  key: smtp_user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ebpf-secrets
                  key: smtp_password

---

apiVersion: v1
kind: Service
metadata:
  name: ebpf-monitor-web-service
  namespace: monitoring
spec:
  selector:
    app: ebpf-monitor-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebpf-monitor-db
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebpf-monitor-db
  template:
    metadata:
      labels:
        app: ebpf-monitor-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ebpf-secrets
                  key: postgres_password
            - name: POSTGRES_DB
              value: monitor_logs
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---

apiVersion: v1
kind: Secret
metadata:
  name: ebpf-secrets
  namespace: monitoring
stringData:
  secret_key: supersecretkey
  smtp_user: user
  smtp_password: password
  postgres_password: postgres