# Dockerfile
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libffi-dev \
    python3-dev \
    bpfcc-tools \
    linux-headers-$(uname -r) \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . /app

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

# Install dependencies
RUN poetry install --no-root

# Expose ports for Flask and Prometheus
EXPOSE 5000 8000

# Start the application
CMD ["poetry", "run", "python", "run.py", "--start"]